language: node_js
node_js:
- 'iojs'
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: PEHwBVlANBR4goE6j5MBNs3xs5XXNnLxYOhgrjaJBhlXCNKOZv2Lx/UTdu4URD51eLhBOO+LXclFdVVp3fDGRRSDQnKsAUwcpFgE8TIBCL3eLRXgfaVYxTLp9DFli7pP69gmgMhJe/6xxlKJMMD2KajSRjRDPOE4FgyFDAU4HdQ=
  app: 
    master: gbptm-api
    develop: gbptm-stage

